# btc.storage.class.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ethereum-disk
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-central1-c
allowVolumeExpansion: true