apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin
  namespace: {{ .Values.namespace.name }} 
spec:
  serviceName: bitcoin
  selector:
    matchLabels:
      app: bitcoin
  replicas: {{ .Values.replicaCount }} 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      restartPolicy: Always
      containers:
        - name: bitcoin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
          - containerPort: 8333
            hostPort: 8333
            protocol: TCP
            name: bitcoin
          - containerPort: 8332
            name: btc-json-rpc
          volumeMounts:
          - name: bitcoin
            mountPath: /root/.bitcoin/
          resources:
            requests:
              memory: "1024M"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: bitcoin
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: bitcoin-disk
        resources:
          requests:
            storage: 80Gi





















# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: stickynotes-deployment
#   labels:
#     app: stickynotes
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   replicas: {{ .Values.replicaCount }} 
#   selector:
#     matchLabels:
#       app: stickynotes-container
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate 
#   template:
#     metadata:
#       labels:
#         app: stickynotes-container
#     spec:
#       containers:
#         - name: stickynotes-container
#           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#           imagePullPolicy: IfNotPresent 
#           resources:
#               requests:
#                 cpu: 50m
#                 memory: 256Mi
#           ports:
#             - containerPort: 8000
#           env:
#             - name: POSTGRES_USER
#               value: postgres
#             - name: POSTGRES_PASSWORD
#               value: postgres

#             - name: POSTGRES_DB
#               value: stickynotesDB

#             - name: POSTGRES_HOST
#               value: 10.244.0.85
              
           
              
    
  
# --- 


  
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: stickynotes-deployment
#   labels:
#     app: stickynotes
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   replicas: {{ .Values.replicaCount }} 
#   selector:
#     matchLabels:
#       app: stickynotes-container
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate 
#   template:
#     metadata:
#       labels:
#         app: stickynotes-container
#     spec:
#       containers:
#         - name: stickynotes-container
#           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#           imagePullPolicy: IfNotPresent 
#           resources:
#               requests:
#                 cpu: 50m
#                 memory: 256Mi
#           ports:
#             - containerPort: 8000
#           env:
#             - name: POSTGRES_USER
#               value: postgres
#             - name: POSTGRES_PASSWORD
#               value: postgres
#             - name: POSTGRES_HOST
#               value: postgres 
#             - name: PGDATA
#               value: /data/pgdata