apiVersion: v1
kind: Service
metadata:
  name: btc-live-svc
  namespace: {{ .Values.namespace.name }} 
spec:
  selector:
    app: btc-live
  ports:
    - protocol: TCP
      port: 8333
      targetPort: 8333
      name: btc-live-net
    - protocol: TCP
      port: 30001
      targetPort: 8332
      name: btc-live-jsonrpc





# apiVersion: v1
# kind: Service
# metadata:
#   name: stickynotes-service
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   selector:
#     app: stickynotes-container
#   ports:
#   - protocol: TCP
#     port: 8000
#     targetPort: 8000
#   type: LoadBalancer

# ---