apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-live
  namespace: {{ .Values.namespace.name }} 
spec:
  serviceName: tezos-live
  selector:
    matchLabels:
      app: tezos-live
  replicas: {{ .Values.replicaCount }} 
  template:
    metadata:
      labels:
        app: tezos-live
    spec:
      containers:
        - name: tezos-live
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
          - containerPort:  8732
            name: tezos-live
          - containerPort:  8735
            name: tezos-json-rpc
          volumeMounts:
          - name: tezos-live-data
            mountPath: /app/data
          resources:
            requests:
              memory: "2048M"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: tezos-live-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: tezos-disk
        resources:
          requests:
            storage: 20Gi
