apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-live
  namespace: {{ .Values.namespace.name }} 
spec:
  serviceName: tezos-live
  selector:
    matchLabels:
      app: tezos-live
  replicas: {{ .Values.replicaCount }} 
  template:
    metadata:
      labels:
        app: tezos-live
    spec:
      hostname: node
      containers:
        - name: tezos-live
          image: {{ .Values.image.repository }}
          command: ["tezos-node"]
          args: ["run"]
          imagePullPolicy: Always
          ports:
          - containerPort: 8733
            name: tezos-live
          - containerPort: 8732
            name: tezos-json-rpc
          volumeMounts:
          - name: tezos-live-data

            mountPath: /app/data
          resources:
            requests:
              memory: "2048M"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: tezos-live-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: tezos-disk
        resources:
          requests:
            storage: 20Gi


















# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: stickynotes-deployment
#   labels:
#     app: stickynotes
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   replicas: {{ .Values.replicaCount }} 
#   selector:
#     matchLabels:
#       app: stickynotes-container
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate 
#   template:
#     metadata:
#       labels:
#         app: stickynotes-container
#     spec:
#       containers:
#         - name: stickynotes-container
#           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#           imagePullPolicy: IfNotPresent 
#           resources:
#               requests:
#                 cpu: 50m
#                 memory: 256Mi
#           ports:
#             - containerPort: 8000
#           env:
#             - name: POSTGRES_USER
#               value: postgres
#             - name: POSTGRES_PASSWORD
#               value: postgres

#             - name: POSTGRES_DB
#               value: stickynotesDB

#             - name: POSTGRES_HOST
#               value: 10.244.0.85
              
           
              
    
  
  
  
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: stickynotes-deployment
#   labels:
#     app: stickynotes
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   replicas: {{ .Values.replicaCount }} 
#   selector:
#     matchLabels:
#       app: stickynotes-container
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate 
#   template:
#     metadata:
#       labels:
#         app: stickynotes-container
#     spec:
#       containers:
#         - name: stickynotes-container
#           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#           imagePullPolicy: IfNotPresent 
#           resources:
#               requests:
#                 cpu: 50m
#                 memory: 256Mi
#           ports:
#             - containerPort: 8000
#           env:
#             - name: POSTGRES_USER
#               value: postgres
#             - name: POSTGRES_PASSWORD
#               value: postgres
#             - name: POSTGRES_HOST
#               value: postgres 
#             - name: PGDATA
#               value: /data/pgdata