
apiVersion: v1
kind: Service
metadata:
  name: tezos-live
  namespace: {{ .Values.namespace.name }} 
spec:
  selector:
    app: tezos-live
  ports:
    - protocol: TCP
      port: 8733
      targetPort: 8733
      name: tezos-live-net
    - protocol: TCP
      port: 8732
      targetPort: 8732
      name: tezos-live-jsonrpc








# apiVersion: v1
# kind: Service
# metadata:
#   name: stickynotes-service
#   namespace: {{ .Values.namespace.name }} 
# spec:
#   selector:
#     app: stickynotes-container
#   ports:
#   - protocol: TCP
#     port: 8000
#     targetPort: 8000
#   type: LoadBalancer

---